### ISSUE TITLE
Review: Create a smaller (simpler) example

### ISSUE THREAD

**Issue by PrashantVaidyanathan** [CSBiology/FSharpGephiStreamer#21]
**Is your feature request related to a problem? Please describe.**
Currently, the there is one example mentioned in the main [project page](https://csbiology.github.io/FSharpGephiStreamer/exampleAnalysis.html)

While this is a very good example of how FSharpGephiStreamer can be used very easily to generate large complex graphs, the runtime is pretty big (or the set up time is too long). 
Users can either
- Parse the CSV files which takes a long time
- Parse the .obo files using BioFSharps which requires users to build the dependencies of BioFSharps. 

**Describe the solution you'd like**
It might be useful to the users if there was a "Hello World" example with very few nodes and edges (perhaps even 5 or 10) that shows how easily the tool can be used. (Preferably something that does not require parsing a large file.)

**Describe alternatives you've considered**
Currently, I am circumventing this issue by selecting just a few nodes from Gene Ontology Example to test and stream.

**Comment by kMutagene** [comment]
Hi @PrashantVaidyanathan ,

While i think the [Streaming section](https://csbiology.github.io/FSharpGephiStreamer/Streaming.html) in the docs is more or less what you are asking for (except the actual execution of the function and an example of the returned result), it's no hassle to add that, will do!

**Comment by kMutagene** [comment]
You can now see a more basic example [here](https://csbiology.github.io/FSharpGephiStreamer/SimpleNetwork.html)
