### ISSUE TITLE
REVIEW: license file naming

### ISSUE THREAD

**Issue by cgravill** [CSBiology/FSharpGephiStreamer#8]
I recommend renaming the license file to not include an extension for compatibility with the GitHub and JOSS naming recommendations:

https://help.github.com/en/articles/adding-a-license-to-a-repository
https://joss.readthedocs.io/en/latest/review_criteria.html#software-license

https://github.com/openjournals/joss-reviews/issues/1445

**Comment by kMutagene** [comment]
Good catch, seems like this applies to all our projects since [ProjectScaffold](https://github.com/fsprojects/ProjectScaffold) (the project layout template we use for all our projects) initializes the license file with a .txt extension.

fixed with #12
